  ; generated by esotope-bfc (DCPU branch)
  SET A, mem
  SET [A], 0
  SET [A+1], 23
  SET [A+2], 0
  SET [A+3], 0
:L0
  IFE [A+1], 0
    SET PC, L1
  SET PUSH, 6
  ADD PEEK, [A+1]
  ADD [A+2], POP
  ADD [A+3], [A+1]
  SET PUSH, 90
  ADD PEEK, [A+2]
  SET [A+1], POP
  SET PUSH, 65535
  ADD PEEK, [A+3]
  SET [A+2], POP
  SET [A+3], 0
  ADD A, 1
  SET PC, L0
:L1
  ADD [A+2], 9
  SET PUSH, 3
  SET B, [A+2]
  MUL B, 9
  ADD PEEK, B
  SET [A+1], POP
  ADD [A+3], 6
  SET PUSH, 65534
  SET B, [A+3]
  SHL B, 3
  ADD PEEK, B
  SET [A+2], POP
  SET PUSH, 65534
  ADD PEEK, [A+2]
  SET [A+3], POP
  ADD [A+4], [A+2]
  SET [A+2], [A+4]
  ADD [A+5], 4
  SET PUSH, 0
  SET B, [A+5]
  SHL B, 3
  ADD PEEK, B
  SET [A+4], POP
  SET [A+5], 10
  ADD [A+6], 9
  SET PUSH, 0
  SET B, [A+6]
  MUL B, 11
  ADD PEEK, B
  ADD [A+7], POP
  SET [A+6], 0
:L2
  IFE [A+7], 0
    SET PC, L3
  ADD [A+8], [A+7]
  ADD [A+9], [A+7]
  ADD [A+10], [A+7]
  SET [A+7], [A+8]
  SET [A+8], 0
:L4
  IFE [A+10], 0
    SET PC, L5
  ADD [A+11], [A+10]
  ADD [A+12], [A+10]
  SET [A+10], [A+12]
  SET [A+12], 0
  IFE [A+11], 0
    SET PC, L6
  SUB [A+11], 1
  SUB [A+10], 1
  IFE [A+11], 0
    SET PC, L7
  SUB [A+11], 1
  SUB [A+10], 1
  IFE [A+11], 0
    SET PC, L8
  SUB [A+11], 1
  SUB [A+10], 1
  IFE [A+11], 0
    SET PC, L9
  SUB [A+11], 1
  SUB [A+10], 1
  IFE [A+11], 0
    SET PC, L10
  SUB [A+11], 1
  SUB [A+10], 1
  IFE [A+11], 0
    SET PC, L11
  SUB [A+11], 1
  SUB [A+10], 1
  IFE [A+11], 0
    SET PC, L12
  SUB [A+11], 1
  SUB [A+10], 1
  IFE [A+11], 0
    SET PC, L13
  SUB [A+11], 1
  SUB [A+10], 1
  IFE [A+11], 0
    SET PC, L14
  SUB [A+11], 1
  SUB [A+10], 1
  IFE [A+11], 0
    SET PC, L15
  SUB [A+10], 1
  ADD [A+8], 1
  SUB [A+9], 10
  SET [A+11], 0
:L15
  SET [A+11], 0
:L14
  SET [A+11], 0
:L13
  SET [A+11], 0
:L12
  SET [A+11], 0
:L11
  SET [A+11], 0
:L10
  SET [A+11], 0
:L9
  SET [A+11], 0
:L8
  SET [A+11], 0
:L7
  SET [A+11], 0
:L6
  SET [A+11], 0
  SET PC, L4
:L5
:L16
  IFE [A+8], 0
    SET PC, L17
  ADD [A+10], 12
  SET PUSH, 0
  SET B, [A+10]
  SHL B, 2
  ADD PEEK, B
  ADD [A+8], POP
  SET PUSH, 0
  SET B, [A+10]
  SHL B, 2
  ADD PEEK, B
  ADD [A+9], POP
  SET [A+10], 0
:L18
  IFE [A+8], 0
    SET PC, L19
  SET B, [A+8]
  JSR putc
  SET [A+8], 0
  ADD A, 1
  SET PC, L18
:L19
  SUB A, 2
  SET PC, L16
:L17
  IFE [A+9], 0
    SET PC, L20
  ADD [A+8], 6
  SET PUSH, 0
  SET B, [A+8]
  SHL B, 3
  ADD PEEK, B
  ADD [A+9], POP
  SET [A+8], 0
  SET B, [A+9]
  JSR putc
  SET [A+9], 0
:L20
  SET [A+9], 0
  SET B, [A+4]
  JSR putc
  SET B, [A+65535]
  JSR putc
:L21
  IFE [A+65535], 0
    SET PC, L22
  SUB A, 1
  SET PC, L21
:L22
  SET B, [A+8]
  JSR putc
  SET B, [A+3]
  JSR putc
  SET B, [A+3]
  JSR putc
  SET B, [A+11]
  JSR putc
  SET B, [A+18]
  JSR putc
:L23
  IFE [A+18], 0
    SET PC, L24
  ADD A, 1
  SET PC, L23
:L24
  ADD [A+20], [A+19]
  ADD [A+21], [A+19]
  SET [A+19], [A+20]
  SET [A+20], 0
  IFE [A+21], 0
    SET PC, L25
  SUB [A+21], 1
  IFE [A+21], 0
    SET PC, L26
  SET [A+21], 0
  ADD [A+20], 0x73
  SET B, [A+20]
  JSR putc
  SET [A+20], 0
:L26
  SET [A+21], 0
:L25
  SET [A+21], 0
  SET B, [A+16]
  JSR putc
:L27
  IFE [A+16], 0
    SET PC, L28
  SUB A, 1
  SET PC, L27
:L28
  SET B, [A+25]
  JSR putc
  SET B, [A+34]
  JSR putc
:L29
  IFE [A+34], 0
    SET PC, L30
  ADD A, 1
  SET PC, L29
:L30
  SET B, [A+32]
  JSR putc
  SET B, [A+27]
  JSR putc
  SET B, [A+24]
  JSR putc
  SET B, [A+24]
  JSR putc
:L31
  IFE [A+24], 0
    SET PC, L32
  SUB A, 1
  SET PC, L31
:L32
  SET B, [A+30]
  JSR putc
:L33
  IFE [A+30], 0
    SET PC, L34
  ADD A, 1
  SET PC, L33
:L34
  SET B, [A+28]
  JSR putc
:L35
  IFE [A+28], 0
    SET PC, L36
  SUB A, 1
  SET PC, L35
:L36
  SET B, [A+37]
  JSR putc
  SET B, [A+38]
  JSR putc
:L37
  IFE [A+38], 0
    SET PC, L38
  ADD A, 1
  SET PC, L37
:L38
  SET B, [A+36]
  JSR putc
:L39
  IFE [A+36], 0
    SET PC, L40
  SUB A, 1
  SET PC, L39
:L40
  SET B, [A+40]
  JSR putc
  SET B, [A+52]
  JSR putc
  SET B, [A+55]
  JSR putc
:L41
  IFE [A+55], 0
    SET PC, L42
  ADD A, 1
  SET PC, L41
:L42
  SET B, [A+53]
  JSR putc
:L43
  IFE [A+53], 0
    SET PC, L44
  SUB A, 1
  SET PC, L43
:L44
  SET B, [A+54]
  JSR putc
:L45
  IFE [A+54], 0
    SET PC, L46
  ADD A, 1
  SET PC, L45
:L46
  SET B, [A+48]
  JSR putc
  SET B, [A+37]
  JSR putc
  SET B, [A+37]
  JSR putc
:L47
  IFE [A+37], 0
    SET PC, L48
  ADD A, 1
  SET PC, L47
:L48
  SET B, [A+34]
  JSR putc
  SET B, [A+35]
  JSR putc
:L49
  IFE [A+35], 0
    SET PC, L50
  ADD A, 1
  SET PC, L49
:L50
  ADD [A+37], [A+36]
  ADD [A+38], [A+36]
  ADD [A+39], [A+36]
  SET [A+36], [A+37]
  SET [A+37], 0
:L51
  IFE [A+39], 0
    SET PC, L52
  ADD [A+40], [A+39]
  ADD [A+41], [A+39]
  SET [A+39], [A+41]
  SET [A+41], 0
  IFE [A+40], 0
    SET PC, L53
  SUB [A+40], 1
  SUB [A+39], 1
  IFE [A+40], 0
    SET PC, L54
  SUB [A+40], 1
  SUB [A+39], 1
  IFE [A+40], 0
    SET PC, L55
  SUB [A+40], 1
  SUB [A+39], 1
  IFE [A+40], 0
    SET PC, L56
  SUB [A+40], 1
  SUB [A+39], 1
  IFE [A+40], 0
    SET PC, L57
  SUB [A+40], 1
  SUB [A+39], 1
  IFE [A+40], 0
    SET PC, L58
  SUB [A+40], 1
  SUB [A+39], 1
  IFE [A+40], 0
    SET PC, L59
  SUB [A+40], 1
  SUB [A+39], 1
  IFE [A+40], 0
    SET PC, L60
  SUB [A+40], 1
  SUB [A+39], 1
  IFE [A+40], 0
    SET PC, L61
  SUB [A+40], 1
  SUB [A+39], 1
  IFE [A+40], 0
    SET PC, L62
  SUB [A+39], 1
  ADD [A+37], 1
  SUB [A+38], 10
  SET [A+40], 0
:L62
  SET [A+40], 0
:L61
  SET [A+40], 0
:L60
  SET [A+40], 0
:L59
  SET [A+40], 0
:L58
  SET [A+40], 0
:L57
  SET [A+40], 0
:L56
  SET [A+40], 0
:L55
  SET [A+40], 0
:L54
  SET [A+40], 0
:L53
  SET [A+40], 0
  SET PC, L51
:L52
:L63
  IFE [A+37], 0
    SET PC, L64
  ADD [A+39], 12
  SET PUSH, 0
  SET B, [A+39]
  SHL B, 2
  ADD PEEK, B
  ADD [A+37], POP
  SET PUSH, 0
  SET B, [A+39]
  SHL B, 2
  ADD PEEK, B
  ADD [A+38], POP
  SET [A+39], 0
:L65
  IFE [A+37], 0
    SET PC, L66
  SET B, [A+37]
  JSR putc
  SET [A+37], 0
  ADD A, 1
  SET PC, L65
:L66
  SUB A, 2
  SET PC, L63
:L64
  IFE [A+38], 0
    SET PC, L67
  ADD [A+37], 6
  SET PUSH, 0
  SET B, [A+37]
  SHL B, 3
  ADD PEEK, B
  ADD [A+38], POP
  SET [A+37], 0
  SET B, [A+38]
  JSR putc
  SET [A+38], 0
:L67
  SET [A+38], 0
  SET B, [A+33]
  JSR putc
  SET B, [A+28]
  JSR putc
:L68
  IFE [A+28], 0
    SET PC, L69
  SUB A, 1
  SET PC, L68
:L69
  SET B, [A+37]
  JSR putc
  SET B, [A+32]
  JSR putc
  SET B, [A+32]
  JSR putc
  SET B, [A+40]
  JSR putc
  SET B, [A+47]
  JSR putc
:L70
  IFE [A+47], 0
    SET PC, L71
  ADD A, 1
  SET PC, L70
:L71
  ADD [A+49], [A+48]
  ADD [A+50], [A+48]
  SET [A+48], [A+49]
  SET [A+49], 0
  IFE [A+50], 0
    SET PC, L72
  SUB [A+50], 1
  IFE [A+50], 0
    SET PC, L73
  SET [A+50], 0
  ADD [A+49], 0x73
  SET B, [A+49]
  JSR putc
  SET [A+49], 0
:L73
  SET [A+50], 0
:L72
  SET [A+50], 0
  SET B, [A+45]
  JSR putc
:L74
  IFE [A+45], 0
    SET PC, L75
  SUB A, 1
  SET PC, L74
:L75
  SET B, [A+54]
  JSR putc
  SET B, [A+63]
  JSR putc
:L76
  IFE [A+63], 0
    SET PC, L77
  ADD A, 1
  SET PC, L76
:L77
  SET B, [A+61]
  JSR putc
  SET B, [A+56]
  JSR putc
  SET B, [A+53]
  JSR putc
  SET B, [A+53]
  JSR putc
:L78
  IFE [A+53], 0
    SET PC, L79
  SUB A, 1
  SET PC, L78
:L79
  SET B, [A+59]
  JSR putc
:L80
  IFE [A+59], 0
    SET PC, L81
  ADD A, 1
  SET PC, L80
:L81
  SET B, [A+55]
  JSR putc
  SET B, [A+58]
  JSR putc
  SET B, [A+54]
  JSR putc
  SET B, [A+53]
  JSR putc
  SET B, [A+43]
  JSR putc
  SET B, [A+49]
  JSR putc
:L82
  IFE [A+49], 0
    SET PC, L83
  ADD A, 1
  SET PC, L82
:L83
  SET B, [A+47]
  JSR putc
:L84
  IFE [A+47], 0
    SET PC, L85
  SUB A, 1
  SET PC, L84
:L85
  SET B, [A+56]
  JSR putc
  SET B, [A+57]
  JSR putc
  SET B, [A+66]
  JSR putc
:L86
  IFE [A+66], 0
    SET PC, L87
  ADD A, 1
  SET PC, L86
:L87
  SET B, [A+64]
  JSR putc
  SET B, [A+57]
  JSR putc
:L88
  IFE [A+57], 0
    SET PC, L89
  SUB A, 1
  SET PC, L88
:L89
  SET B, [A+66]
  JSR putc
:L90
  IFE [A+66], 0
    SET PC, L91
  SUB A, 1
  SET PC, L90
:L91
  SET B, [A+67]
  JSR putc
  SET B, [A+76]
  JSR putc
:L92
  IFE [A+76], 0
    SET PC, L93
  ADD A, 1
  SET PC, L92
:L93
  SET B, [A+74]
  JSR putc
  SET B, [A+70]
  JSR putc
  SET B, [A+57]
  JSR putc
:L94
  IFE [A+57], 0
    SET PC, L95
  ADD A, 1
  SET PC, L94
:L95
  SET B, [A+48]
  JSR putc
:L96
  IFE [A+48], 0
    SET PC, L97
  ADD A, 1
  SET PC, L96
:L97
  SET B, [A+46]
  JSR putc
:L98
  IFE [A+46], 0
    SET PC, L99
  SUB A, 1
  SET PC, L98
:L99
  SET B, [A+54]
  JSR putc
:L100
  IFE [A+54], 0
    SET PC, L101
  ADD A, 1
  SET PC, L100
:L101
  SET B, [A+48]
  JSR putc
:L102
  IFE [A+48], 0
    SET PC, L103
  SUB A, 1
  SET PC, L102
:L103
  SET B, [A+53]
  JSR putc
  SET B, [A+53]
  JSR putc
:L104
  IFE [A+53], 0
    SET PC, L105
  ADD A, 1
  SET PC, L104
:L105
  SET B, [A+51]
  JSR putc
  SET B, [A+39]
  JSR putc
:L106
  IFE [A+39], 0
    SET PC, L107
  SUB A, 1
  SET PC, L106
:L107
  SET B, [A+43]
  JSR putc
:L108
  IFE [A+43], 0
    SET PC, L109
  ADD A, 1
  SET PC, L108
:L109
  SET B, [A+41]
  JSR putc
  SET B, [A+37]
  JSR putc
:L110
  IFE [A+37], 0
    SET PC, L111
  SUB A, 1
  SET PC, L110
:L111
  SET B, [A+43]
  JSR putc
  SET B, [A+46]
  JSR putc
  SET B, [A+40]
  JSR putc
  SET B, [A+47]
  JSR putc
  SET B, [A+57]
  JSR putc
:L112
  IFE [A+57], 0
    SET PC, L113
  ADD A, 1
  SET PC, L112
:L113
  SET B, [A+54]
  JSR putc
  SET B, [A+55]
  JSR putc
  SUB [A+58], 1
  ADD [A+59], [A+58]
  ADD [A+60], [A+58]
  ADD [A+61], [A+58]
  SET [A+58], [A+59]
  SET [A+59], 0
:L114
  IFE [A+61], 0
    SET PC, L115
  ADD [A+62], [A+61]
  ADD [A+63], [A+61]
  SET [A+61], [A+63]
  SET [A+63], 0
  IFE [A+62], 0
    SET PC, L116
  SUB [A+62], 1
  SUB [A+61], 1
  IFE [A+62], 0
    SET PC, L117
  SUB [A+62], 1
  SUB [A+61], 1
  IFE [A+62], 0
    SET PC, L118
  SUB [A+62], 1
  SUB [A+61], 1
  IFE [A+62], 0
    SET PC, L119
  SUB [A+62], 1
  SUB [A+61], 1
  IFE [A+62], 0
    SET PC, L120
  SUB [A+62], 1
  SUB [A+61], 1
  IFE [A+62], 0
    SET PC, L121
  SUB [A+62], 1
  SUB [A+61], 1
  IFE [A+62], 0
    SET PC, L122
  SUB [A+62], 1
  SUB [A+61], 1
  IFE [A+62], 0
    SET PC, L123
  SUB [A+62], 1
  SUB [A+61], 1
  IFE [A+62], 0
    SET PC, L124
  SUB [A+62], 1
  SUB [A+61], 1
  IFE [A+62], 0
    SET PC, L125
  SUB [A+61], 1
  ADD [A+59], 1
  SUB [A+60], 10
  SET [A+62], 0
:L125
  SET [A+62], 0
:L124
  SET [A+62], 0
:L123
  SET [A+62], 0
:L122
  SET [A+62], 0
:L121
  SET [A+62], 0
:L120
  SET [A+62], 0
:L119
  SET [A+62], 0
:L118
  SET [A+62], 0
:L117
  SET [A+62], 0
:L116
  SET [A+62], 0
  SET PC, L114
:L115
:L126
  IFE [A+59], 0
    SET PC, L127
  ADD [A+61], 12
  SET PUSH, 0
  SET B, [A+61]
  SHL B, 2
  ADD PEEK, B
  ADD [A+59], POP
  SET PUSH, 0
  SET B, [A+61]
  SHL B, 2
  ADD PEEK, B
  ADD [A+60], POP
  SET [A+61], 0
:L128
  IFE [A+59], 0
    SET PC, L129
  SET B, [A+59]
  JSR putc
  SET [A+59], 0
  ADD A, 1
  SET PC, L128
:L129
  SUB A, 2
  SET PC, L126
:L127
  IFE [A+60], 0
    SET PC, L130
  ADD [A+59], 6
  SET PUSH, 0
  SET B, [A+59]
  SHL B, 3
  ADD PEEK, B
  ADD [A+60], POP
  SET [A+59], 0
  SET B, [A+60]
  JSR putc
  SET [A+60], 0
:L130
  SET [A+60], [A+58]
  ADD [A+59], [A+58]
  SET [A+58], [A+59]
  SET [A+59], 1
  IFE [A+60], 0
    SET PC, L131
  SUB [A+59], 1
  SET [A+60], 0
:L131
  SET [A+60], 0
:L132
  IFE [A+59], 0
    SET PC, L133
  SUB [A+59], 1
:L134
  IFE [A+56], 0
    SET PC, L135
  SUB A, 1
  SET PC, L134
:L135
  SET B, [A+66]
  JSR putc
  SET B, [A+65]
  JSR putc
:L136
  IFE [A+65], 0
    SET PC, L137
  ADD A, 1
  SET PC, L136
:L137
  SET B, [A+63]
  JSR putc
:L138
  IFE [A+63], 0
    SET PC, L139
  SUB A, 1
  SET PC, L138
:L139
  SET B, [A+74]
  JSR putc
  SET B, [A+72]
  JSR putc
  SET B, [A+69]
  JSR putc
:L140
  IFE [A+69], 0
    SET PC, L141
  ADD A, 1
  SET PC, L140
:L141
  SET B, [A+59]
  JSR putc
:L142
  IFE [A+59], 0
    SET PC, L143
  ADD A, 1
  SET PC, L142
:L143
  ADD A, 2
  SET PC, L132
:L133
  SET B, [A+55]
  JSR putc
  SET B, [A+50]
  JSR putc
:L144
  IFE [A+50], 0
    SET PC, L145
  SUB A, 1
  SET PC, L144
:L145
  SET B, [A+59]
  JSR putc
  SET B, [A+54]
  JSR putc
  SET B, [A+54]
  JSR putc
  SET B, [A+62]
  JSR putc
  SET B, [A+69]
  JSR putc
:L146
  IFE [A+69], 0
    SET PC, L147
  ADD A, 1
  SET PC, L146
:L147
  ADD [A+71], [A+70]
  ADD [A+72], [A+70]
  SET [A+70], [A+71]
  SET [A+71], 1
  IFE [A+72], 0
    SET PC, L148
  SUB [A+72], 1
  SUB [A+71], 1
  IFE [A+72], 0
    SET PC, L149
  ADD [A+71], 1
  SET [A+72], 0
:L149
  SET [A+72], 0
:L148
  SET [A+72], 0
  IFE [A+71], 0
    SET PC, L150
  ADD [A+71], 8
  SET PUSH, 2
  SET B, [A+71]
  MUL B, 13
  SUB PEEK, B
  SUB [A+72], POP
  SET [A+71], 0
  SET B, [A+72]
  JSR putc
  SET [A+72], 0
:L150
  SET [A+71], 0
  SET B, [A+67]
  JSR putc
:L151
  IFE [A+67], 0
    SET PC, L152
  SUB A, 1
  SET PC, L151
:L152
  SET B, [A+76]
  JSR putc
  SET B, [A+85]
  JSR putc
:L153
  IFE [A+85], 0
    SET PC, L154
  ADD A, 1
  SET PC, L153
:L154
  SET B, [A+83]
  JSR putc
  SET B, [A+78]
  JSR putc
  SET B, [A+75]
  JSR putc
  SET B, [A+75]
  JSR putc
:L155
  IFE [A+75], 0
    SET PC, L156
  SUB A, 1
  SET PC, L155
:L156
  SET B, [A+81]
  JSR putc
:L157
  IFE [A+81], 0
    SET PC, L158
  ADD A, 1
  SET PC, L157
:L158
  SET B, [A+79]
  JSR putc
:L159
  IFE [A+79], 0
    SET PC, L160
  SUB A, 1
  SET PC, L159
:L160
  SET B, [A+88]
  JSR putc
  SET B, [A+89]
  JSR putc
:L161
  IFE [A+89], 0
    SET PC, L162
  ADD A, 1
  SET PC, L161
:L162
  SET B, [A+87]
  JSR putc
:L163
  IFE [A+87], 0
    SET PC, L164
  SUB A, 1
  SET PC, L163
:L164
  SET B, [A+91]
  JSR putc
  SET B, [A+103]
  JSR putc
  SET B, [A+106]
  JSR putc
:L165
  IFE [A+106], 0
    SET PC, L166
  ADD A, 1
  SET PC, L165
:L166
  SET B, [A+104]
  JSR putc
:L167
  IFE [A+104], 0
    SET PC, L168
  SUB A, 1
  SET PC, L167
:L168
  SET B, [A+105]
  JSR putc
:L169
  IFE [A+105], 0
    SET PC, L170
  ADD A, 1
  SET PC, L169
:L170
  SET B, [A+99]
  JSR putc
  SET B, [A+88]
  JSR putc
  SET B, [A+88]
  JSR putc
:L171
  IFE [A+88], 0
    SET PC, L172
  ADD A, 1
  SET PC, L171
:L172
  SET B, [A+84]
  JSR putc
  SET B, [A+87]
  JSR putc
  SET B, [A+87]
  JSR putc
  ADD A, 82
  SET PC, L2
:L3
  SUB PC, 1
:screenoff
  DAT 0
:newline
  SET C, [screenoff]
  AND C, 0xffe0
  ADD C, 0x20
  SET [screenoff], C
  IFG 0x180, C
    SET PC, POP
:scroll
  SET C, 0
:scroll_loop
  SET [C+0x8000], [C+0x8020]
  ADD C, 1
  IFG 0x160, C
    SET PC, scroll_loop
:scroll_loop2
  SET [C+0x8000], 0
  ADD C, 1
  IFG 0x180, C
    SET PC, scroll_loop2
  SUB [screenoff], 0x20
  SET PC, POP
:putc
  IFE B, 10
    SET PC, newline
  IFG [screenoff], 0x17e
    JSR scroll
  SET C, [screenoff]
  BOR B, 0xf000
  SET [C+0x8000], B
  ADD C, 1
  SET [screenoff], C
  SET PC, POP
:mem
  DAT 0  ; the start of memory
